# Generated by Django 5.1.1 on 2024-10-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
