# Generated by Django 5.1.1 on 2024-10-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_transport_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='image_path',
        ),
        migrations.AddField(
            model_name='transport',
            name='image_extension',
            field=models.CharField(default='jpg', max_length=5),
        ),
    ]
