# Generated by Django 5.1.1 on 2024-10-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_remove_transport_image_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='image_extension',
        ),
        migrations.AddField(
            model_name='transport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='transport_images/'),
        ),
    ]
