# Generated by Django 5.1.1 on 2024-10-04 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_remove_transport_image_extension_transport_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='image',
        ),
    ]
